#' Fit penalized regression model.
#' 
#' @param object TO BE EDITED.
#' @return A list, the model and the cross validated model.
#' @export
fit_model.easy_glinternet <- function(object) {
  warning("Warning: This is for demo purposes; fit_model for glinternet needs a tweak or two to adhere to best practices.")
  # set model arguments
  model_args <- object[["model_args"]]
  
  # process model_args
  X <- as.matrix(object[["X"]])
  model_args[["X"]] <- X
  model_args[["Y"]] <- object[["y"]]
  model_args[["family"]] <- object[["family"]]
  model_args[["numLevels"]] <- rep(1, ncol(X))

  # build model
  model <- do.call(glinternet::glinternet, model_args)
  object[["model"]] <- model

  # write output
  object
}

#' Extract coefficients from a penalized regression model.
#' 
#' @param object TO BE EDITED.
#' @return A data.frame of replicated penalized regression coefficients.
#' @export
extract_coefficients.easy_glinternet <- function(object) {
  stop("Error: extract_coefficients not implemented.")
}

#' Predict values for a penalized regression model.
#' 
#' @param results The results of \code{\link{fit_model}}.
#' @param newx A data.frame, the new data to use for predictions.
#' @return A vector, the predicted values for a penalized regression model using the new data.
#' @export
predict_model.easy_glinternet <- function(object, newx = NULL) {
  newx <- as.matrix(newx)
  model <- object[["model"]]
  stats::predict(model, X = newx)
}

#' Easily build and evaluate a penalized regression model with interactions.
#'
#' @param ... Arguments to be passed to \code{\link[glinternet]{glinternet}} or \code{\link[glinternet]{cv.glinternet}}. See those functions' documentation for more details on possible arguments and what they mean. Examples of applicable arguments are \code{alpha}, \code{nlambda}, \code{nlambda.min.ratio}, \code{lambda}, \code{standardize}, \code{intercept}, \code{thresh}, \code{dfmax}, \code{pmax}, \code{exclude}, \code{penalty.factor}, \code{lower.limits}, \code{upper.limits}, \code{maxit}, and \code{standardize.response} for \code{\link[glinternet]{glinternet}} and \code{weights}, \code{offset}, \code{lambda}, \code{type.measure}, \code{nfolds}, \code{foldid}, \code{grouped}, \code{keep}, \code{parallel} for \code{\link[glinternet]{cv.glinternet}}.
#' @inheritParams easy_analysis
#' @return A list with the following values:
#' \describe{
#' \item{resample}{A function; the function for resampling the data.}
#' \item{preprocess}{A function; the function for preprocessing the data.}
#' \item{measure}{A function; the function for measuring the results.}
#' \item{fit_model}{A function; the function for fitting the model to the data.}
#' \item{extract_coefficients}{A function; the function for extracting coefficients from the model.}
#' \item{predict_model}{A function; the function for generating predictions on new data from the model.}
#' \item{plot_predictions}{A function; the function for plotting predictions generated by the model.}
#' \item{plot_metrics}{A function; the function for plotting metrics generated by scoring the model.}
#' \item{data}{A data.frame; the original data.}
#' \item{X}{A data.frame; the full dataset to be used for modeling.}
#' \item{y}{A vector; the full response variable to be used for modeling.}
#' \item{X_train}{A data.frame; the train dataset to be used for modeling.}
#' \item{X_test}{A data.frame; the test dataset to be used for modeling.}
#' \item{y_train}{A vector; the train response variable to be used for modeling.}
#' \item{y_test}{A vector; the test response variable to be used for modeling.}
#' \item{coefficients}{A (n_variables, n_samples) matrix; the replicated coefficients.}
#' \item{coefficients_processed}{A data.frame; the coefficients after being processed.}
#' \item{plot_coefficients_processed}{A ggplot object; the plot of the processed coefficients.}
#' \item{predictions_train}{A (nrow(X_train), n_samples) matrix; the train predictions.}
#' \item{predictions_test}{A (nrow(X_test), n_samples) matrix; the test predictions.}
#' \item{predictions_train_mean}{A vector; the mean train predictions.}
#' \item{predictions_test_mean}{A vector; the mean test predictions.}
#' \item{plot_predictions_train_mean}{A ggplot object; the plot of the mean train predictions.}
#' \item{plot_predictions_test_mean}{A ggplot object; the plot of the mean test predictions.}
#' \item{metrics_train_mean}{A vector of length n_divisions; the mean train metrics.}
#' \item{metrics_test_mean}{A vector of length n_divisions; the mean test metrics.}
#' \item{plot_metrics_train_mean}{A ggplot object; the plot of the mean train metrics.}
#' \item{plot_metrics_test_mean}{A ggplot object; the plot of the mean test metrics.}
#' }
#' @family recipes
#' @examples 
#' library(easyml) # https://github.com/CCS-Lab/easyml
#' 
#' # Gaussian
#' data("prostate", package = "easyml")
#' results <- easy_glinternet(prostate, "lpsa", 
#'                        n_samples = 10, n_divisions = 10, 
#'                        n_iterations = 2, random_state = 12345, 
#'                        n_core = 1, alpha = 1.0)
#' 
#' # Binomial
#' data("cocaine_dependence", package = "easyml")
#' results <- easy_glinternet(cocaine_dependence, "diagnosis", 
#'                        family = "binomial", 
#'                        exclude_variables = c("subject"), 
#'                        categorical_variables = c("male"), 
#'                        preprocess = preprocess_scale, 
#'                        n_samples = 10, n_divisions = 10, 
#'                        n_iterations = 2, random_state = 12345, 
#'                        n_core = 1, alpha = 1.0)
#' @export
easy_glinternet <- function(.data, dependent_variable, family = "gaussian", 
                        resample = NULL, preprocess = preprocess_scale, 
                        measure = measure_r2_score, 
                        exclude_variables = NULL, categorical_variables = NULL, 
                        train_size = 0.667, foldid = NULL, 
                        survival_rate_cutoff = 0.05, 
                        n_samples = 1000, n_divisions = 1000, 
                        n_iterations = 10, random_state = NULL, 
                        progress_bar = TRUE, n_core = 1, 
                        coefficients = FALSE, variable_importances = FALSE, 
                        predictions = TRUE, metrics = TRUE, 
                        model_args = list()) {
  easy_analysis(.data, dependent_variable, algorithm = "glinternet", 
                family = family, resample = resample, 
                preprocess = preprocess, measure = measure, 
                exclude_variables = exclude_variables, 
                categorical_variables = categorical_variables,  
                train_size = train_size, foldid = foldid,  
                survival_rate_cutoff = survival_rate_cutoff, 
                n_samples = n_samples, n_divisions = n_divisions, 
                n_iterations = n_iterations, random_state = random_state, 
                progress_bar = progress_bar, n_core = n_core, 
                coefficients = coefficients, 
                variable_importances = variable_importances, 
                predictions = predictions, metrics = metrics, 
                model_args = model_args)
}
