#' Fit random forest gaussian regression model.
#' 
#' @param X a data frame or a matrix of predictors, or a formula describing the model to be fitted (for the print method, an randomForest object).
#' @param y A response vector. If a factor, classification is assumed, otherwise regression is assumed. If omitted, randomForest will run in unsupervised mode.
#' @param ... Arguments to be passed to \code{\link[randomForest]{randomForest}}. See that function's documentation for more details.
#' @return TO BE EDITED.
#' @export
random_forest_fit_model_gaussian <- function(X, y, ...) {
  X <- as.matrix(X)
  randomForest::randomForest(X, y, ...)
}

#' Fit random forest binomial regression model.
#' 
#' @param X a data frame or a matrix of predictors, or a formula describing the model to be fitted (for the print method, an randomForest object).
#' @param y A response vector. If a factor, classification is assumed, otherwise regression is assumed. If omitted, randomForest will run in unsupervised mode.
#' @param ... Arguments to be passed to \code{\link[randomForest]{randomForest}}. See that function's documentation for more details.
#' @return TO BE EDITED.
#' @export
random_forest_fit_model_binomial <- function(X, y, ...) {
  X <- as.matrix(X)
  y <- factor(y)
  randomForest::randomForest(X, y, ...)
}

#' Predict values for a random forest regression model.
#' 
#' @param results TO BE EDITED.
#' @param newx TO BE EDITED.
#' @return TO BE EDITED.
#' @export
random_forest_predict_model <- function(results, newx) {
  as.numeric(stats::predict(results, newdata = newx))
}

#' Easily build and evaluate a random forest regression model.
#' 
#' @param ... Arguments to be passed to \code{\link[randomForest]{randomForest}}. See that function's documentation for more details.
#' @inheritParams easy_analysis
#' @return A list with the following values:
#' \describe{
#' \item{resample}{A function; the function for resampling the data.}
#' \item{preprocess}{A function; the function for preprocessing the data.}
#' \item{measure}{A function; the function for measuring the results.}
#' \item{fit_model}{A function; the function for fitting the model to the data.}
#' \item{extract_coefficients}{A function; the function for extracting coefficients from the model.}
#' \item{predict_model}{A function; the function for generating predictions on new data from the model.}
#' \item{plot_predictions}{A function; the function for plotting predictions generated by the model.}
#' \item{plot_metrics}{A function; the function for plotting metrics generated by scoring the model.}
#' \item{data}{A data.frame; the original data.}
#' \item{X}{A data.frame; the full dataset to be used for modeling.}
#' \item{y}{A vector; the full response variable to be used for modeling.}
#' \item{X_train}{A data.frame; the train dataset to be used for modeling.}
#' \item{X_test}{A data.frame; the test dataset to be used for modeling.}
#' \item{y_train}{A vector; the train response variable to be used for modeling.}
#' \item{y_test}{A vector; the test response variable to be used for modeling.}
#' \item{predictions_train}{A (nrow(X_train), n_samples) matrix; the train predictions.}
#' \item{predictions_test}{A (nrow(X_test), n_samples) matrix; the test predictions.}
#' \item{predictions_train_mean}{A vector; the mean train predictions.}
#' \item{predictions_test_mean}{A vector; the mean test predictions.}
#' \item{plot_predictions_train_mean}{A ggplot object; the plot of the mean train predictions.}
#' \item{plot_predictions_test_mean}{A ggplot object; the plot of the mean test predictions.}
#' \item{metrics_train_mean}{A vector of length n_divisions; the mean train metrics.}
#' \item{metrics_test_mean}{A vector of length n_divisions; the mean test metrics.}
#' \item{plot_metrics_train_mean}{A ggplot object; the plot of the mean train metrics.}
#' \item{plot_metrics_test_mean}{A ggplot object; the plot of the mean test metrics.}
#' }
#' @family recipes
#' @examples 
#' library(easyml) # https://github.com/CCS-Lab/easyml
#' 
#' # Gaussian
#' data("prostate", package = "easyml")
#' results <- easy_random_forest(prostate, "lpsa", 
#'                               n_samples = 10L, 
#'                               n_divisions = 10, 
#'                               n_iterations = 2, 
#'                               random_state = 12345, n_core = 1)
#' 
#' # Binomial
#' data("cocaine_dependence", package = "easyml")
#' results <- easy_random_forest(cocaine_dependence, "diagnosis", 
#'                               family = "binomial", 
#'                               exclude_variables = c("subject"),
#'                               categorical_variables = c("male"),
#'                               n_samples = 10, 
#'                               n_divisions = 10, 
#'                               n_iterations = 2, 
#'                               random_state = 12345, n_core = 1)
#' @export
easy_random_forest <- function(.data, dependent_variable, family = "gaussian", 
                               resample = NULL, preprocess = NULL, measure = NULL, 
                               exclude_variables = NULL, categorical_variables = NULL, 
                               train_size = 0.667, 
                               n_samples = 1000, n_divisions = 1000, 
                               n_iterations = 10, random_state = NULL, 
                               progress_bar = TRUE, n_core = 1, ...) {
  easy_analysis(.data, dependent_variable, algorithm = "random_forest", 
                family = family, resample = resample, 
                preprocess = preprocess, measure = measure, 
                exclude_variables = exclude_variables, 
                categorical_variables = categorical_variables,  
                train_size = train_size, 
                n_samples = n_samples, n_divisions = n_divisions, 
                n_iterations = n_iterations, random_state = random_state, 
                progress_bar = progress_bar, n_core = n_core, ...)
}
