#' Fit support vector machine gaussian regression model.
#'
#' @param X a data matrix, a vector, or a sparse matrix (object of class Matrix provided by the Matrix package, or of class matrix.csr provided by the SparseM package, or of class simple_triplet_matrix provided by the slam package).
#' @param y a response vector with one label for each row/component of x. Can be either a factor (for classification tasks) or a numeric vector (for regression).
#' @param ... Arguments to be passed to \code{\link[e1071]{svm}}. See that function's documentation for more details.
#' @return TO BE EDITED.
#' @export
support_vector_machine_fit_model_gaussian <- function(X, y, ...) {
  X <- as.matrix(X)
  e1071::svm(X, y, scale = FALSE, type = "nu-regression", ...)
}

#' Fit support vector machine binomial regression model.
#' 
#' @param X a data matrix, a vector, or a sparse matrix (object of class Matrix provided by the Matrix package, or of class matrix.csr provided by the SparseM package, or of class simple_triplet_matrix provided by the slam package).
#' @param y a response vector with one label for each row/component of x. Can be either a factor (for classification tasks) or a numeric vector (for regression).
#' @param ... Arguments to be passed to \code{\link[e1071]{svm}}. See that function's documentation for more details.
#' @return TO BE EDITED.
#' @export
support_vector_machine_fit_model_binomial <- function(X, y, ...) {
  X <- as.matrix(X)
  y <- factor(y)
  e1071::svm(X, y, scale = FALSE, type = "C-classification", ...)
}

#' Predict values for a support vector machine regression model.
#' 
#' @param results TO BE EDITED.
#' @param newx TO BE EDITED.
#' @return TO BE EDITED.
#' @export
support_vector_machine_predict_model <- function(results, newx) {
  as.numeric(stats::predict(results, newdata = newx))
}

#' Easily build and evaluate a support vector machine regression model.
#'
#'@param ... Arguments to be passed to \code{\link[e1071]{svm}}. See that function's documentation for more details.
#' @inheritParams easy_analysis
#' @return A list with the following values:
#' \describe{
#' \item{resample}{A function; the function for resampling the data.}
#' \item{preprocess}{A function; the function for preprocessing the data.}
#' \item{measure}{A function; the function for measuring the results.}
#' \item{fit_model}{A function; the function for fitting the model to the data.}
#' \item{extract_coefficients}{A function; the function for extracting coefficients from the model.}
#' \item{predict_model}{A function; the function for generating predictions on new data from the model.}
#' \item{plot_predictions}{A function; the function for plotting predictions generated by the model.}
#' \item{plot_metrics}{A function; the function for plotting metrics generated by scoring the model.}
#' \item{data}{A data.frame; the original data.}
#' \item{X}{A data.frame; the full dataset to be used for modeling.}
#' \item{y}{A vector; the full response variable to be used for modeling.}
#' \item{X_train}{A data.frame; the train dataset to be used for modeling.}
#' \item{X_test}{A data.frame; the test dataset to be used for modeling.}
#' \item{y_train}{A vector; the train response variable to be used for modeling.}
#' \item{y_test}{A vector; the test response variable to be used for modeling.}
#' \item{predictions_train}{A (nrow(X_train), n_samples) matrix; the train predictions.}
#' \item{predictions_test}{A (nrow(X_test), n_samples) matrix; the test predictions.}
#' \item{predictions_train_mean}{A vector; the mean train predictions.}
#' \item{predictions_test_mean}{A vector; the mean test predictions.}
#' \item{plot_predictions_train_mean}{A ggplot object; the plot of the mean train predictions.}
#' \item{plot_predictions_test_mean}{A ggplot object; the plot of the mean test predictions.}
#' \item{metrics_train_mean}{A vector of length n_divisions; the mean train metrics.}
#' \item{metrics_test_mean}{A vector of length n_divisions; the mean test metrics.}
#' \item{plot_metrics_train_mean}{A ggplot object; the plot of the mean train metrics.}
#' \item{plot_metrics_test_mean}{A ggplot object; the plot of the mean test metrics.}
#' }
#' @family recipes
#' @examples 
#' library(easyml) # https://github.com/CCS-Lab/easyml
#' 
#' # Gaussian
#' data("prostate", package = "easyml")
#' results <- easy_support_vector_machine(prostate, "lpsa", 
#'                                        n_samples = 10L, 
#'                                        n_divisions = 10L, 
#'                                        n_iterations = 2L, 
#'                                        random_state = 1L, n_core = 1L)
#' 
#' # Binomial
#' data("cocaine_dependence", package = "easyml")
#' results <- easy_support_vector_machine(cocaine_dependence, "diagnosis", 
#'                                        family = "binomial", 
#'                                        preprocesss = preprocess_scale, 
#'                                        exclude_variables = c("subject"), 
#'                                        categorical_variables = c("male"), 
#'                                        n_samples = 10L, 
#'                                        n_divisions = 10L, 
#'                                        n_iterations = 2L, 
#'                                        random_state = 1L, n_core = 1L)
#' @export
easy_support_vector_machine <- function(.data, dependent_variable, family = "gaussian", 
                     resample = NULL, preprocess = NULL, measure = NULL, 
                     exclude_variables = NULL, categorical_variables = NULL, 
                     train_size = 0.667, 
                     n_samples = 1000L, n_divisions = 1000L, 
                     n_iterations = 10L, random_state = NULL, 
                     progress_bar = TRUE, n_core = 1L, ...) {
  easy_analysis(.data, dependent_variable, algorithm = "support_vector_machine", 
                family = family, resample = resample, 
                preprocess = preprocess, measure = measure, 
                exclude_variables = exclude_variables, 
                categorical_variables = categorical_variables,  
                train_size = train_size, 
                n_samples = n_samples, n_divisions = n_divisions, 
                n_iterations = n_iterations, random_state = random_state, 
                progress_bar = progress_bar, n_core = n_core, ...)
}
